name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP client
        run: sudo apt-get install -y ncftp

      - name: Deploy to cPanel
        run: |
          ncftpput -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} -R -v ${{ secrets.FTP_SERVER }} /public_html/dist ./dist
