name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP client
        run: sudo apt-get install -y ncftp

      - name: Deploy to cPanel
        run: |
          ncftpput -u issmai -p 628KrISbn0uQ:[ -R -v 49.12.122.233 /public_html ./dist
